name: sns
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main 
jobs:


  deploy_source:
    name: sns
    runs-on: ubuntu-latest
    steps :
      - name: Publish SNS Topic
        uses: nothingalike/sns-publish-topic@v1.6
        with:
          MESSAGE: "message"
          TOPIC_ARN: "arn:aws:sns:us-east-1:918874519898:project"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
